% DESIGN_LQR_ALL_TARGETS
% Phase 7 official MATLAB script.
% It loads A and B from Phase 6, designs one local LQR controller for each
% target mode, prints closed-loop eigenvalues, and exports gains to JSON and MAT.
%
% Control law used by Python:
%     u = -K * wrapped_error_state
%     u is saturated to [-15 N, +15 N] before it enters the nonlinear plant.

clear; clc;

root_dir = fileparts(fileparts(mfilename('fullpath')));
linearization_path = fullfile(root_dir, 'shared', 'linearization', 'linearized_models.json');
export_dir = fullfile(root_dir, 'shared', 'lqr');
if ~exist(export_dir, 'dir')
    mkdir(export_dir);
end
json_export_path = fullfile(export_dir, 'lqr_gains.json');
mat_export_path = fullfile(export_dir, 'lqr_gains.mat');

if ~exist(linearization_path, 'file')
    error('Phase 6 linearization file not found: %s', linearization_path);
end

raw_text = fileread(linearization_path);
data = jsondecode(raw_text);

modes = {'up_up', 'up_down', 'down_up'};
state_order = {'x', 'x_dot', 'theta1', 'theta1_dot', 'theta2', 'theta2_dot'};

% State order: x, x_dot, theta1, theta1_dot, theta2, theta2_dot.
% Angle weights are highest because this controller is only for local balance.
Q = diag([2.0, 1.0, 180.0, 12.0, 180.0, 12.0]);
R = 0.8;

controllers = struct();
K_all = struct();
eig_all = struct();

fprintf('Phase 7 - local LQR design\n');
fprintf('Using Q = diag([2, 1, 180, 12, 180, 12]) and R = 0.8\n\n');

for i = 1:numel(modes)
    mode = modes{i};
    model = data.models.(mode);
    A = phase18_json_matrix(model.A, [6, 6], sprintf('%s.A', mode));
    B = phase18_json_matrix(model.B, [6, 1], sprintf('%s.B', mode));

    % MATLAB lqr requires Control System Toolbox. The care fallback is useful
    % when lqr is unavailable but care exists.
    if exist('lqr', 'file') == 2
        K = lqr(A, B, Q, R);
    else
        [P, ~, ~] = care(A, B, Q, R);
        K = R \ (B' * P);
    end

    eig_values = eig(A - B * K);

    controllers.(mode).mode = mode;
    controllers.(mode).K = K;
    controllers.(mode).Q = Q;
    controllers.(mode).R = R;
    controllers.(mode).closed_loop_eigenvalues = [real(eig_values), imag(eig_values)];
    controllers.(mode).note = 'Official gain generated by MATLAB Phase 7 script.';

    K_all.(mode) = K;
    eig_all.(mode) = eig_values;

    fprintf('%s\n', mode);
    fprintf('K = '); disp(K);
    fprintf('closed-loop eigenvalues = '); disp(eig_values.');
end

export_data = struct();
export_data.source = 'MATLAB script matlab/design_lqr_all_targets.m';
export_data.state_order = state_order;
export_data.input_order = {'cart_force_N'};
export_data.control_law = 'u = -K * wrapped_error_state, then saturate to [-15 N, +15 N]';
export_data.controllers = controllers;

json_text = jsonencode(export_data, PrettyPrint=true);
fid = fopen(json_export_path, 'w');
fprintf(fid, '%s', json_text);
fclose(fid);

save(mat_export_path, 'controllers', 'K_all', 'eig_all', 'Q', 'R', 'state_order');

fprintf('\nSaved JSON: %s\n', json_export_path);
fprintf('Saved MAT:  %s\n', mat_export_path);

function M = phase18_json_matrix(value, expected_size, name)
    %PHASE18_JSON_MATRIX Convert jsondecode output into a numeric MATLAB matrix.
    % Different MATLAB versions decode JSON nested arrays differently:
    %   - some return a numeric double matrix directly
    %   - some return a cell array of numeric rows
    % This helper accepts both forms so design_lqr_all_targets can read
    % shared/linearization/linearized_models.json reliably.

    if isnumeric(value)
        M = double(value);
    elseif iscell(value)
        if isempty(value)
            M = [];
        elseif all(cellfun(@isnumeric, value))
            row_count = numel(value);
            first_row = value{1};
            if isrow(first_row)
                col_count = numel(first_row);
                M = zeros(row_count, col_count);
                for r = 1:row_count
                    row = value{r};
                    if numel(row) ~= col_count
                        error('Invalid JSON matrix %s: row %d has inconsistent length.', name, r);
                    end
                    M(r, :) = reshape(double(row), 1, []);
                end
            else
                M = cell2mat(value);
            end
        else
            M = cell2mat(value);
        end
    else
        error('Invalid JSON matrix %s: unsupported decoded type %s.', name, class(value));
    end

    if isvector(M) && expected_size(2) == 1 && numel(M) == expected_size(1)
        M = M(:);
    end

    if ~isequal(size(M), expected_size)
        error('Invalid JSON matrix %s: expected size %dx%d but got %dx%d.', ...
            name, expected_size(1), expected_size(2), size(M, 1), size(M, 2));
    end

    if any(~isfinite(M(:)))
        error('Invalid JSON matrix %s: contains NaN or Inf.', name);
    end
end

