% RUN_OPEN_LOOP_COMPARE Phase 20 open-loop nonlinear plant smoke test.
%
% Purpose:
%   - Run the MATLAB nonlinear plant without any controller.
%   - Use the same state order and angle convention as Python Phase 17.
%   - Optionally compare against a Python reference CSV generated by
%     scripts/phase20_generate_python_open_loop_reference.py.
%
% State order:
%   [x, x_dot, theta1, theta1_dot, theta2, theta2_dot]
%
% Angle convention:
%   theta = 0 rad means downward, theta = pi rad means upright.
%
% How to run from project root:
%   run('matlab/startup_project.m')
%   run('matlab/simulation/run_open_loop_compare.m')

clearvars -except ans;

% Resolve paths from this script location. Do not call run('matlab/startup_project.m')
% with a relative path here, because MATLAB's run() changes into this script
% folder before executing the file. A relative nested run would otherwise look
% for matlab/simulation/matlab/startup_project.m.
this_file = mfilename('fullpath');
simulation_dir = fileparts(this_file);
matlab_root = fileparts(simulation_dir);
run(fullfile(matlab_root, 'startup_project.m'));

[params, meta] = load_params();

out_dir = fullfile(meta.project_root, 'results', 'phase20_open_loop_compare');
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

% Fixed-step RK4 is used instead of ode45 so the MATLAB result can be compared
% directly with the Python fixed-step reference.
dt = 0.005;
t_final = 5.0;
t = (0:dt:t_final).';
n = numel(t);

% Small perturbation around downward-downward. This is intentionally open-loop
% and not a stabilize/swing-up test.
x0 = [0.0; 0.0; 0.18; 0.0; -0.12; 0.0];

x_hist = zeros(n, 6);
u_hist = zeros(n, 1);
x_hist(1, :) = x0.';

for k = 1:(n - 1)
    tk = t(k);
    xk = x_hist(k, :).';
    uk = local_open_loop_input(tk);
    u_hist(k) = uk;

    k1 = dip_dynamics_nonlinear(xk, uk, params);
    k2 = dip_dynamics_nonlinear(xk + 0.5 * dt * k1, local_open_loop_input(tk + 0.5 * dt), params);
    k3 = dip_dynamics_nonlinear(xk + 0.5 * dt * k2, local_open_loop_input(tk + 0.5 * dt), params);
    k4 = dip_dynamics_nonlinear(xk + dt * k3, local_open_loop_input(tk + dt), params);

    x_next = xk + (dt / 6.0) * (k1 + 2*k2 + 2*k3 + k4);

    if any(~isfinite(x_next))
        error('run_open_loop_compare:NonFiniteState', ...
              'State became NaN or Inf at step %d, t = %.4f.', k, tk);
    end

    x_hist(k + 1, :) = x_next.';
end
u_hist(end) = local_open_loop_input(t(end));

matlab_csv = fullfile(out_dir, 'matlab_open_loop.csv');
T = table(t, x_hist(:, 1), x_hist(:, 2), x_hist(:, 3), x_hist(:, 4), x_hist(:, 5), x_hist(:, 6), u_hist, ...
          'VariableNames', {'t', 'x', 'x_dot', 'theta1', 'theta1_dot', 'theta2', 'theta2_dot', 'u'});
writetable(T, matlab_csv);

summary_file = fullfile(out_dir, 'matlab_open_loop_summary.txt');
fid = fopen(summary_file, 'w');
if fid < 0
    error('run_open_loop_compare:FileOpenFailed', 'Cannot open summary file for writing.');
end
cleanup_obj = onCleanup(@() fclose(fid));

fprintf(fid, 'Phase 20 MATLAB open-loop nonlinear plant test\n');
fprintf(fid, 'State order: [x, x_dot, theta1, theta1_dot, theta2, theta2_dot]\n');
fprintf(fid, 'Angle convention: theta = 0 downward, theta = pi upright\n');
fprintf(fid, 'dt = %.6f s\n', dt);
fprintf(fid, 't_final = %.6f s\n', t_final);
fprintf(fid, 'max_abs_state = %.12g\n', max(abs(x_hist(:))));
fprintf(fid, 'max_abs_u = %.12g\n', max(abs(u_hist)));
fprintf(fid, 'final_state = [%s]\n', sprintf(' %.12g', x_hist(end, :)));

reference_csv = fullfile(out_dir, 'python_open_loop_reference.csv');
if isfile(reference_csv)
    R = readtable(reference_csv);
    ref = [R.x, R.x_dot, R.theta1, R.theta1_dot, R.theta2, R.theta2_dot];
    if height(R) == n
        max_abs_diff = max(abs(x_hist(:) - ref(:)));
        fprintf(fid, 'python_reference = found\n');
        fprintf(fid, 'max_abs_diff_vs_python = %.12g\n', max_abs_diff);
        if max_abs_diff < 1e-8
            fprintf(fid, 'compare_result = PASS\n');
        elseif max_abs_diff < 1e-5
            fprintf(fid, 'compare_result = PASS_WITH_SMALL_NUMERICAL_DIFF\n');
        else
            fprintf(fid, 'compare_result = CHECK_DIFF\n');
        end
    else
        fprintf(fid, 'python_reference = found_but_length_mismatch\n');
        fprintf(fid, 'compare_result = CHECK_REFERENCE_LENGTH\n');
    end
else
    fprintf(fid, 'python_reference = not_found\n');
    fprintf(fid, 'compare_result = MATLAB_ONLY_SMOKE_PASS_IF_NO_NAN_INF\n');
end

clear cleanup_obj;

fig = figure('Name', 'Phase 20 MATLAB Open Loop Compare', 'Color', 'w');
tiledlayout(4, 1);

nexttile;
plot(t, x_hist(:, 1), 'LineWidth', 1.2);
grid on;
ylabel('x [m]');
title('Phase 20 open-loop MATLAB nonlinear plant');

nexttile;
plot(t, x_hist(:, 3), 'LineWidth', 1.2);
hold on;
plot(t, x_hist(:, 5), 'LineWidth', 1.2);
grid on;
ylabel('angle [rad]');
legend('theta1', 'theta2', 'Location', 'best');

nexttile;
plot(t, x_hist(:, 2), 'LineWidth', 1.2);
hold on;
plot(t, x_hist(:, 4), 'LineWidth', 1.2);
plot(t, x_hist(:, 6), 'LineWidth', 1.2);
grid on;
ylabel('velocity');
legend('x dot', 'theta1 dot', 'theta2 dot', 'Location', 'best');

nexttile;
plot(t, u_hist, 'LineWidth', 1.2);
grid on;
ylabel('u [N]');
xlabel('time [s]');

saveas(fig, fullfile(out_dir, 'matlab_open_loop_plot.png'));

fprintf('Phase 20 run_open_loop_compare: PASS\n');
fprintf('Saved MATLAB CSV: %s\n', matlab_csv);
fprintf('Saved summary:    %s\n', summary_file);
fprintf('Saved plot:       %s\n', fullfile(out_dir, 'matlab_open_loop_plot.png'));

function u = local_open_loop_input(t)
    % Keep input small and smooth. This phase tests plant consistency, not control.
    u = 1.5 * sin(2*pi*0.45*t) + 0.35 * sin(2*pi*1.2*t);
end
