function graph = transitionGraphLibrary(params)

    if nargin < 1 || isempty(params)
        params = loadParams();
    end

    target_lib = targetEquilibriumLibrary(params);

    node_names = {'down_down', 'up_up', 'up_down', 'down_up'};
    node_ids = {'EP0', 'EP1', 'EP2', 'EP3'};

    nodes = struct();
    for i = 1:numel(node_names)
        name = node_names{i};
        item = target_lib.targets.(name);
        node = struct();
        node.id = node_ids{i};
        node.name = name;
        node.index = i;
        node.target_state = item.target_state(:);
        node.theta_targets_rad = item.theta_targets_rad;
        node.description = item.description;
        nodes.(name) = node;
    end

    edge_list = {};
    edges = struct();
    count = 0;
    for i = 1:numel(node_names)
        for j = 1:numel(node_names)
            if i == j
                continue;
            end
            count = count + 1;
            source = node_names{i};
            target = node_names{j};
            edge_name = sprintf('%s_to_%s', source, target);

            edge = struct();
            edge.name = edge_name;
            edge.index = count;
            edge.source = source;
            edge.target = target;
            edge.source_id = nodes.(source).id;
            edge.target_id = nodes.(target).id;
            edge.x0 = nodes.(source).target_state(:);
            edge.xf = nodes.(target).target_state(:);
            edge.state_order = target_lib.state_order;
            edge.angle_convention = target_lib.angle_convention;
            edge.priority = local_edge_priority(source, target);
            edge.priority_group = local_priority_group(edge.priority);
            edge.default_final_time_s = local_default_final_time(source, target);
            edge.recommended_N = local_recommended_mesh(edge.default_final_time_s);
            edge.force_reserve_required_N = 2.0;
            edge.trajectory_file_name = sprintf('transition_%s_tracking_ready.mat', edge_name);
            edge.result_prefix = sprintf('transitionLibrary_%s', edge_name);
            edge.description = sprintf('Transition %s (%s) -> %s (%s)', ...
                source, edge.source_id, target, edge.target_id);

            edges.(edge_name) = edge;
            edge_list{end + 1} = edge_name; %#ok<AGROW>
        end
    end

    graph = struct();
    graph.workflow = 'transition library';
    graph.source = 'matlab/control/transitionGraphLibrary.m';
    graph.nodes = nodes;
    graph.node_order = node_names;
    graph.node_ids = node_ids;
    graph.edges = edges;
    graph.edge_order = edge_list;
    graph.priority_edges = {'down_down_to_up_up', 'up_up_to_up_down', 'up_up_to_down_up'};
    graph.switching_return_edges = {'up_down_to_up_up', 'down_up_to_up_up'};
    graph.switching_switching_demo_edges = {'down_down_to_up_up', 'up_up_to_up_down', 'up_down_to_up_up', 'up_up_to_down_up', 'down_up_to_up_up'};
    graph.all_directed_transition_count = numel(edge_list);
    graph.state_order = target_lib.state_order;
    graph.angle_convention = target_lib.angle_convention;
    graph.theta2_definition = 'theta2 is an absolute angle from the downward vertical direction';
    graph.notes = ['transition library optimizes priority edges first. switching demo return edges are ', ...
                   'up_down_to_up_up and down_up_to_up_up. Remaining edges are graph-defined ', ...
                   'and can be generated by passing edge_names to run_transitionLibrary_generate_transition_library.'];
end

function priority = local_edge_priority(source, target)
    if strcmp(source, 'down_down') && strcmp(target, 'up_up')
        priority = 1;
    elseif strcmp(source, 'up_up') && (strcmp(target, 'up_down') || strcmp(target, 'down_up'))
        priority = 1;
    elseif strcmp(target, 'up_up')
        priority = 2;
    else
        priority = 3;
    end
end

function label = local_priority_group(priority)
    switch priority
        case 1
            label = 'transitionLibrary_priority';
        case 2
            label = 'important_return_edge';
        otherwise
            label = 'full_graph_extension';
    end
end

function T = local_default_final_time(source, target)
    if strcmp(source, 'down_down') && strcmp(target, 'up_up')
        T = 8.0;
    elseif strcmp(source, 'up_up') || strcmp(target, 'up_up')
        T = 5.0;
    else
        T = 5.5;
    end
end

function N = local_recommended_mesh(T)
    dt_nominal = 0.10;
    N = round(T / dt_nominal) + 1;
    N = max(41, min(81, N));
end
