function cfg = defaultRecoveryConfig(project_root, user_cfg)
    if nargin < 1 || isempty(project_root)
        project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    if nargin < 2 || isempty(user_cfg)
        user_cfg = struct();
    end
    resume = false;
    if isfield(user_cfg, 'resume')
        resume = logical(user_cfg.resume);
    end
    cfg = struct();
    cfg.project_root = project_root;
    cfg.recovery_mode = 'CONSTRAINED_TRAJECTORY_TRACKING';
    cfg.recovery_label = 'RECOVERY_MATRIX_CONSTRAINED_TRACKING';
    cfg.recovery_reset_matrix_checkpoint = ~resume;
    cfg.recovery_resume_matrix = resume;
    cfg.recovery_clear_failed_state_csv_on_reset = true;
    cfg.recovery_save_failed_cases = true;
    cfg.recovery_force_levels_N = [1.0];
    cfg.force_levels_N = [1.0];
    cfg.post_switching_force_levels_N = [1.0];
    cfg.nominal_force_levels_N = [1.0];
    cfg.stress_force_levels_N = [];
    cfg.recovery_roaRouter_nominal_opt_forces_N = [1.0];
    cfg.recovery_angle_rad = 0.10;
    cfg.recovery_velocity_norm = 0.90;
    cfg.recovery_cart_abs_m = 1.80;
    cfg.global_cart_limit_m = 1.95;
    cfg.max_saturation_fraction = 0.70;
    cfg.settle_hold_s = 0.20;
    cfg.min_target_success_rate = 0.95;
    cfg.min_post_switching_success_rate = 0.95;
    cfg.sim_time_s = 19.0;
    cfg.recovery_upup_hard_extra_time_s = 5.5;
    cfg.post_switching_settle_time_s = 3.0;
    cfg.recovery_require_existing_switching_result = true;
    cfg.recovery_best50_lock_enable = true;
    cfg.recovery_best50_lock_csv = fullfile(project_root, 'results', 'recoveryBaseline', 'best50_all_metrics.csv');
    cfg.recovery_constrainedRecovery_enable = true;
    cfg.recovery_constrainedRecoverya2_microbrake_enable = true;
    cfg.recovery_constrainedRecoveryb_upup_hardstate_enable = true;
    cfg.recovery_constrainedRecovery_library_mat = fullfile(project_root, 'shared', 'recovery_trajectories_constrainedRecovery', 'recovery_constrainedRecovery_hardstate_library.mat');
    cfg.recovery_constrainedRecoverya2_horizon_s = 0.62;
    cfg.recovery_constrainedRecoverya2_guard_abs_m = 1.82;
    cfg.recovery_constrainedRecoverya2_release_abs_m = 1.68;
    cfg.recovery_constrainedRecoverya2_kd = 9.5;
    cfg.recovery_constrainedRecoverya2_kp = 16.0;
    cfg.recovery_constrainedRecoverya2_pulse_fraction = 0.34;
    cfg.recovery_constrainedRecoverya2_max_brake_blend = 0.58;
    cfg.recovery_constrainedRecoverya2_lqr_keep = 0.96;
    cfg.recovery_constrainedRecoverya2_angle_rate_damp = 0.20;
    cfg.recovery_constrainedRecovery_roa_angle_rad = 0.32;
    cfg.recovery_constrainedRecovery_roa_velocity_norm = 1.65;
    cfg.recovery_railBrakeFallback_enable = true;
    cfg.recovery_balanceFallback_enable = true;
    cfg.recovery_balanceFallbacka_rail_only_enable = true;
    cfg.recovery_balanceFallbackb_upup_directed_enable = true;
    cfg.recovery_roa_traj_tvlqr_enable = true;
    cfg.recovery_enable_offline_trajectory_planner = true;
    cfg.recovery_candidate_competition = true;
    cfg.recovery_traj_takeover_enable = true;
    cfg.recovery_force_takeover_on_local_fail = true;
    cfg.recovery_force_takeover_on_priority_fail_state = true;
    cfg.recovery_select_failed_nonlocal_for_debug = true;
    cfg.recovery_traj_takeover_min_pass_first = true;
    cfg.recovery_no_silent_local_fallback = true;
    cfg.recovery_failstate_ratio_gate = 0.75;
    cfg.recovery_roaRouter_priority_targets = {'up_up','down_up'};
    cfg.recovery_roa_traj_priority_link_id = 2;
    cfg.recovery_roa_traj_priority_contact_ratio = 0.75;
    cfg.recovery_roa_traj_try_roa_score = 3.50;
    cfg.recovery_roa_traj_try_saturation_fraction = 0.30;
    cfg.recovery_roa_traj_try_peak_cart_abs_m = 1.45;
    cfg.recovery_roa_traj_allow_safe_improved_failed_candidate = false;
    cfg.recovery_hardStateFallback_constrained_hardstate_enable = false;
    cfg.recovery_enable_opt_library = false;
    cfg.recovery_enable_optimized_library = false;
    cfg.recovery_auto_build_optimized_library = false;
    cfg.recovery_disable_direct_trajopt_takeover = true;
    cfg.recovery_enable_rail_safety_filter = true;
    cfg.recovery_enable_early_global_rail_barrier = false;
    cfg.recovery_cart_safety_abs_m = 1.40;
    cfg.recovery_cart_priority_abs_m = 1.40;
    cfg.recovery_rail_emergency_abs_m = 1.82;
    cfg.recovery_rail_guard_kp = 10.0;
    cfg.recovery_rail_guard_kd = 4.0;
    cfg.recovery_rail_emergency_kp = 18.0;
    cfg.recovery_state_specific_gain_search_enable = false;
    cfg.recovery_hard_state_library_enable = true;
    cfg.recovery_terminal_recovery_enable = true;
    cfg.recovery_terminal_soft_u_fraction = 0.88;
    cfg.recovery_terminal_brake_soft_u_fraction = 0.82;
    fields = fieldnames(user_cfg);
    for k = 1:numel(fields)
        cfg.(fields{k}) = user_cfg.(fields{k});
    end
end
